feat:  split to elements
htmlacademy-ecmascript/997093-cinemaddict-16 pull request #4
Opened 2021-11-30 19:08 UTC by kildim

(cherry picked from commit 63c882e7a5020bfede52a278f248b4f2a19a4722)

2021-12-01 13:24 UTC, babtshe requested changes

2021-12-01 13:24 UTC, babtshe commented on src/render.js
> +};
Зачем выносить в константы встроенные значения? Какая от этого польза?

2021-12-01 13:24 UTC, babtshe commented on src/render.js
> +export const renderTemplate = (container, template, place) => {
тут хорошо бы использовать значение по умолчанию.

2021-12-01 13:24 UTC, babtshe commented on src/utils.js
> +// Источник - https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_random
есть смысл оставлять такие комментарии, только если по ссылке есть какая-то дополнительная информация, которая поможет пониманию кода.

2021-12-01 16:16 UTC, kildim commented on src/render.js
> +};
Подсмотрел у авторов курса 😉. Они так в демпроекте поступили!

2021-12-01 16:18 UTC, kildim commented on src/utils.js
> +// Источник - https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_random
Слизано с демпроекта, типо уважение к проперти :)

2021-12-02 06:52 UTC, babtshe approved these changes

2021-12-02 06:52 UTC, merged